### ISSUE TITLE
Python error in SVD Registers view

### ISSUE THREAD

**Issue by danielRep** [burrbull/gdb-dashboard-svdregisters#1]
Hi @burrbull ,

I'm trying to use your dashboard module, but I have some issues while configuring a setup for it. 
What I have I done so far was:

1. Copy svdregisters.py in .gdbinit.d folder.
2. Copy my SVD file into .gdbinit.d folder (Musca_B1.svd).
3. Create a _registers.txt_ file with the first line containing the filename of the SVD, i.e., `Musca_B1.svd`.
4. Start pyocd and connect arm-none-eabi-gdb-py (v8.3.1), i.e., `target remote :3333`.

From this point forward I see this output on SVD Registers view:
![image](https://user-images.githubusercontent.com/19411211/141997925-31d9195a-dacb-4c35-b448-5fe4db048252.png)

What am I missing?

**Comment by burrbull** [comment]
I did not use this tool for 2 years, so it can be incompatible with current `gdb-dashboard`. I've remembered about it only a week ago. I'll try to check what is wrong.

Possibly it is make sense to add `gdb-dashboard` as git submodule.

**Comment by burrbull** [comment]
Try this version first:
https://github.com/cyrus-and/gdb-dashboard/tree/04d60768e6d558d5d9898b8455f7055b9b59d48e

**Comment by danielRep** [comment]
I have just confirmed that with that version, I don't get that python error. However, now I am seeing this output after performing the command:
`dashboard svdregisters monitor SAU`

```
>>> dashboard svdregisters monitor SAU
Cannot open or parse SVD file. Check 'cmsis_svd' library installed
```
Afaik, I need to install the cmsis_svd package, which I did though pip (v20.0.2, python3.8), but without luck. Any ideas?

**Comment by burrbull** [comment]
What you mean `but without luck`?
You can't install `cmsis_svd`?

**Comment by burrbull** [comment]
If you've installed `cmsis_svd` try this manually where `SvdRegisters.FILE` is "path/to/registers.txt":
https://github.com/burrbull/gdb-dashboard-svdregisters/blob/029b7361914ef0670cc1051cabf52f0d8b15eaa3/svdregisters.py#L184-L189

**Comment by danielRep** [comment]
> What you mean `but without luck`? You can't install `cmsis_svd`?

I can install the cmsis_svd, but I still get the same error ("Cannot open or parse SVD file. Check 'cmsis_svd' library installed")
```
daniel@daniel-N56VZ:~$ pip show cmsis_svd
Name: cmsis-svd
Version: 0.4
Summary: CMSIS SVD data files and parser
Home-page: https://github.com/posborne/cmsis-svd
Author: Paul Osborne
Author-email: osbpau@gmail.com
License: Apache 2.0
Location: /home/daniel/.local/lib/python3.8/site-packages
Requires: six
Required-by: 
```

**Comment by burrbull** [comment]
Try to use this SVD https://raw.githubusercontent.com/nickray/muscab1-pac/master/musca-b1.svd.patched
with (change path):
```
 18:32 ❯ cat registers.txt       
/home/burrbull/tests/musca-b1.svd.patched
GPIO0.DATA _ 0x41000000
```

**Comment by burrbull** [comment]
`registers.txt` should be in folder where you run `arm-none-eabi-gdb` from (project folder)
same as SVD

**Comment by danielRep** [comment]
I have changed the `registers.txt` and placed both in my home root, where I am running `arm-non-eabi-gdb-py`.

As soons as I start gdb-py I got these errors:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 458, in start
  File "<string>", line 508, in parse_inits
gdb.error: /home/daniel/.gdbinit.d/musca-b1.svd:1: Error in sourced command file:
Undefined command: "<device".  Try "help".
/home/daniel/.gdbinit:1663: Error in sourced command file:
Error while executing Python code.
```

After connecting to the target (`target remote :3333`) and enabling dashboard (`dashboard -enabled on`), this is the traceback in SVD Registers view

![image](https://user-images.githubusercontent.com/19411211/142017670-8b611d38-7cdf-4e88-9db5-985f78ac9399.png)

**Comment by danielRep** [comment]
Okey, I just solved the SVD register view error. It was related with `mem inaccessible-by-default` which was on. By setting off (`set mem inaccessible-by-default off`), I can now see an output:

![image](https://user-images.githubusercontent.com/19411211/142020515-2ef50e13-7792-4a3f-893b-e65454a0fda4.png)

I would like to solve the monitor issue, which will probably be related with `gdb` not having the path for the `cmsis_svd` module in `sys.path` (I am not familiarize with python, so I could be wrong)

**Comment by burrbull** [comment]
You want to see all registers in peripheral? I've added such possibility. But it should be ease.
Now you need to add registers by one:
`dashboard svdregisters monitor SAU.CTRL`
or field only:
`... monitor  SAU.CTRL.ENABLE`

**Comment by danielRep** [comment]
I got this output error:

```
>>> dashboard svdregisters monitor SAU.RBAR
global name 'find_recursive' is not defined
>>> dashboard svdregisters monitor SAU.type
global name 'find_recursive' is not defined

```

**Comment by burrbull** [comment]
find_recursive is static method
pull last commit

**Comment by danielRep** [comment]
Still getting the problem with the missing `cmsis_svd` library. Supposedly, the path to the library is already in sys.path. 

```
>>> dashboard svdregisters monitor SAU.RBAR
Cannot open or parse SVD file. Check 'cmsis_svd' library installed
>>> dashboard svdregisters monitor SAU.TYPE
Cannot open or parse SVD file. Check 'cmsis_svd' library installed
>>> pi
>>> print(sys.path)
['/home/daniel/toolchains/arm/gcc-arm-none-eabi-9-2020-q2-update/arm-none-eabi/share/gdb/python', '/home/daniel', '/home/daniel/.local/lib/python3.8/site-packages/cmsis_svd', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/libsigrok-0.6.0-py2.7-linux-x86_64.egg', '/usr/lib/python2.7/dist-packages']
>>> 

```

**Comment by burrbull** [comment]
I split this error on 3 different. Pull again (and restart). I can't test as I don't have any device now.

**Comment by danielRep** [comment]
I pulled again and restarted as you asked. I also changed to the `gdb-multiarch` and now I can see the `sys.path` pointing to the site-packages where `cmsis_svd` sits. Therefore, the missing library error disappear, but I got another error:

```
>>> pi
>>> import sys
>>> print(sys.path)
['/usr/share/gdb/python', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/daniel/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
>>> import cmsis_svd
>>> 
>>> dashboard svdregisters monitor SAU.TYPE
name 'find_recursive' is not defined
```

**Comment by burrbull** [comment]
Moved find_recursive out of class. Try again

**Comment by danielRep** [comment]
Just pulled and tried again. Not working still :\

```
>>> dashboard svdregisters monitor SAU.TYPE
name 'find_recursive' is not defined
```

However, other commands like `dashboard svdregisters bin` or  `dashboard svdregisters decimal` are working.

**Comment by burrbull** [comment]
I'm really don't understand how it can be not defined

**Comment by burrbull** [comment]
Anyway you can edit registers.txt manually like:
```
 21:21 ❯ cat registers.txt
/home/burrbull/tests/musca-b1.svd.patched
SAU.TYPE _ 0xe000edd4
SAU.RBAR _ 0xe000eddc
```

or with gtk based tool
![изображение](https://user-images.githubusercontent.com/3072754/142043803-808ef30f-322e-4829-bb2e-583cda548f48.png)

**Comment by danielRep** [comment]
Yes, I will use that method. Thanks for the help!

**Comment by danielRep** [comment]
@burrbull , one last question. How can I run the GUI after building ?

**Comment by burrbull** [comment]
You can find binary file in `target/release` directory.
`cd` to your project dir and run it from there.

**Comment by danielRep** [comment]
Thank you @burrbull , with that plugin is easier to generate the registers.

**Comment by burrbull** [comment]
`monitor` command should be fixed. Pull again

**Comment by burrbull** [comment]
Also updated to use last `gdb-dashboard`

**Comment by danielRep** [comment]
I have tested and its working @burrbull . Thanks! Closing the issue.
